FORMAT: 1A
HOST: http://www.mcdonald.cz

# McD Notify
McD Notify je služba pro předávání změn obsahu stránek společnosti [McDonald CZ](http://www.mcdonald.cz) a [McDonald SK](https://www.mcdonalds.sk/) do infrastruktury společnosti Anywhere. Data jsou následně využívána 
mobilní aplikací. Předávány jsou tyto informace:

1. novinky
1. tiskové zprávy
1. restaurace
1. produkty
1. vouchery

Informace jsou předávány v okamžiku jejich zveřejnění na www.mcdonald.cz. Předání navazuje na publikační proces a sdílí stejná data. Pokud tedy dojde např. ke zveřejnění novinky, 
obsah novinky je následně předán přes McD Notify. V případě, že je upravováno více informací současně (např. změny v nutričních hodnotách více produktů a publikování celého seznamu),
jsou změněná data předávána postupným voláním API pro každou položku.

## Data obsahu
Informace jsou předávány ve formátu *json*. Každý záznam je identifikován *ID*, které je unikátní pro daný typ záznamu (např. mezi restauracemi). 
Dále záznam obsahuje datum poslední změny, informaci o jazykové mutaci *location* ( *cz* nebo *sk* ) a další specifické informace.

### Novinky
    {
        id : 1,
        location : "cz",
        created : "20.10.2014 13:13:06",
        updated: "21.10.2014 11:17:17",
        title : "Snack It Easy!",
        photo : "https://www.mcdonalds.cz/img/cs/novinky/snack-it-easy.jpg",
        url : "https://www.mcdonalds.cz/cs/novinky/snack-it-easy.shtml",
        status : "2",
    }

### Tiskové zprávy

    {
        id : 1,
        location : "cz",
        created : "3.2.2012 13:13:06",
        updated: "14.2.2012 11:17:17",
        title : "McDonald's otevřel první restauraci ve Frýdku-Místku",
        subtitle : "",
        perex : "Společnost McDonald's slavnostně otevřela první restauraci ve Frýdku-Místku v ulici Na Příkopě.",
        body : "<p>Včera proběhlo slavnostní otevření restaurace McDonald's ve Frýdku-Místku za přítomnosti mnoha hostů. Zúčastnily se osobnosti z řad zástupců města Frýdek-Místek, podnikatelské sféry, sportovního světa, projekčních a stavebních firem a dalších institucí, které se podílely na výstavbě restaurace, včetně vedení společnosti McDonald's ČR/SR. Jmenujme např. náměstky primátora města Frýdek-Místek pana Libora Kovalu a Mgr. Michala Pobuckého, DiS., hokejisty HC Oceláři Třinec Václava Varaďu a Jana Peterka, ředitele ostravské pobočky Komerční Banky Mgr. Jiřího Mohylu nebo zástupce UniCredit Bank Ing. Marka Luzara.</p>",
        status : "2",
    }


### Restaurace

    {
        id : 52,
        location : "cz",
        updated: "10.10.2014 10:10:10",
        region : 10,
        lat : 50.0511061,
        lng : 14.4382528,
        name : "McDonald's",
        category : "2;8;6;12",
        address : "Obchodní centrum Arkády Pankrác, Na Pankráci 86, Praha 4 140 00",
        tel : "725 573 061",
        fax : "",
        photo : "http://www.mcdonalds.cz/img/edee/restaurace/52/img_0439.jpg",
        openingHours : "Po - Pá: 7 - 21,<br>So - Ne: 8 - 21",
        openingHoursDrive : "",
        services : "12;2",
        info : "Nepřijímá stravenky Exit Group."
    }

### Produkty

    {
        id : 1,
        location : "cz",
        updated: "10.10.2014 10:10:10",
        title : "Hamburger",
        perex : "<p>Stálice naší nabídky. Mleté hovězí maso s&nbsp;nakládanou okurkou, kečupem a&nbsp;hořčicí. Pšeničná žemle.</p>",
        type : "sandwich",
        category : "mcdonalds",
        icon : "http://www.mcdonalds.cz/img/u/produkty/sendvice/ico/hamburger.png",
        photo : "http://www.mcdonalds.cz/img/u/produkty/sendvice/hd/hamburger.png",
        ingredients : ["Mleté hovězí maso", "Pšeničná žemle", "Kečup", "Hořčice", "Nakládaná okurka", "Cibule" ],
        nutrition : [{type : "calories", value : "255", label : "kcal"}, {type : "protein", value : "13", label : "bílkoviny"}, {type : "fat", value : "9", label : "tuky"}],
        allergens : ["Lepek", "Sezam", "Hořčice"]
    }

### Vouchery

    {
        id : 1,
        location : "cz",
        updated: "10.10.2014 10:10:10",
        title : "1 + 1 Chicken McNuggets™ 6 ks",
        photo : "http://www.mcdonalds.cz/img/cs/novinky/slavte-s-nami-nejvyhodneji/kupony/kupon-01.jpg",
        media : ["http://www.mcdonalds.cz/swf/u/novinky/kuponovka/kupon_04.swf"],
        validFrom : "1.9.2014",
        validTo : "30.9.2014"
    }
    

## Aktualizace záznamů
Pokud není záznam s *ID* nalezen, vytvoří se nový. Pokud již záznam existuje, dojde k jeho aktualizaci.

## Návratové hodnoty
V případě úspěšného zpracování dat vrací API hodnotu stavu, například *HTTP Response Status 200 OK*. 

## Chybové stavy
V případě chyby vrací API jiný stav než *2xx* společně s informací o chybě. Možné stavové kódy jsou *400 BAD REQ, 410 GONE, 404 NOT FOUND, 500 INTERNAL ERROR*.  


Informace obsahuje kód chyby a lokalizovanou chybovou zprávu. Příklad
    400 Bad Request
    
    {
        code: 10,
        message: "Neplatný formát dat, chybí povinná položka 'ID'. "
    }


## Zabezpečení API
Komunikace s API je šifrovaná, probíha přes protokol HTTPS. Identifikace uživatele je provedena pomocí HTTP Basic autentizace. Autentizační hlavička je součástí každého odeslaného požadavku
na API.

# Group Restaurace
API pro předávání aktualizovaného seznamu restaurací.

## Restaurace [/restaurants/{id}]

+ Model (application/json)

    Informace o restauraci a stavu aktualizace

    + Body
    
            {
                id : 52,
                location : "cz",
                updated: "10.10.2014 10:10:10",
                region : 10,
                lat : 50.0511061,
                lng : 14.4382528,
                name : "McDonald's",
                address : "Obchodní centrum Arkády Pankrác, Na Pankráci 86, Praha 4 140 00",
                tel : "725 573 061",
                fax : "",
                photo : "http://www.mcdonalds.cz/img/edee/restaurace/52/img_0439.jpg",
                openingHours : "Po - Pá: 7 - 21,<br>So - Ne: 8 - 21",
                openingHoursDrive : "",
                services : "12;2",
                info : "Nepřijímá stravenky Exit Group."
            }
    

### Změna / přidání restaurace [POST]
+ Request 

    [Restaurace][]

+ Response 200
+ Response 201

### Smazání restaurace [DELETE]

+ Parameters
    + id (string) ... ID restaurace, která má být smazaná.

+ Response 204

## Služby [/restaurants/services]

### Číselník služeb nabízených restauracemi [PUT]

+ Request (application/json)

        [{
            id:2,
            location : "cz",
            name: "Snídaně",
            description : "V této restauraci se můžete nasnídat...",
            icon : "https://www.mcdonalds.cz/img/u/map/ico/services/1.png"
        }]
        
+ Response 200
+ Response 201

# Group Novinky

API pro předávání aktualizovaného seznamu novinek.

## Novinky [/news/{id}]

### Změna / přidání  novinky [POST]

Součástí předávané zprávy je i status. Ten nabývá následujících hodnot:

 1. v přípravě
 1. k publikaci
 1. ke schválení
 1. zrušit zveřejnění
 
+ Request (application/json)

        {
            id : 1,
            location : "cz",
            created : "20.10.2014 13:13:06",
            updated: "21.10.2014 11:17:17",
            title : "Snack It Easy!",
            photo : "https://www.mcdonalds.cz/img/cs/novinky/snack-it-easy.jpg",
            url : "https://www.mcdonalds.cz/cs/novinky/snack-it-easy.shtml",
            status : "2",
        }

+ Response 200
+ Response 201

### Smazání novinky [DELETE]

+ Parameters
    + id (string) ... ID novinky, která má být smazaná.

+ Response 204

# Group Tiskové zprávy

API pro předávání aktualizovaného seznamu tiskových zpráv.

## Tiskové zprávy [/press/{id}]

### Změna / přidání  tiskové zprávy [POST]

Součástí předávané zprávy je i status. Ten nabývá následujících hodnot:

 1. v přípravě
 1. k publikaci
 1. ke schválení
 1. zrušit zveřejnění
 
+ Request (application/json)

        {
            id : 1,
            location : "cz",
            created : "3.2.2012 13:13:06",
            updated: "14.2.2012 11:17:17",
            title : "McDonald's otevřel první restauraci ve Frýdku-Místku",
            subtitle : "",
            perex : "Společnost McDonald's slavnostně otevřela první restauraci ve Frýdku-Místku v ulici Na Příkopě.",
            body : "<p>Včera proběhlo slavnostní otevření restaurace McDonald's ve Frýdku-Místku za přítomnosti mnoha hostů. Zúčastnily se osobnosti z řad zástupců města Frýdek-Místek, podnikatelské sféry, sportovního světa, projekčních a stavebních firem a dalších institucí, které se podílely na výstavbě restaurace, včetně vedení společnosti McDonald's ČR/SR. Jmenujme např. náměstky primátora města Frýdek-Místek pana Libora Kovalu a Mgr. Michala Pobuckého, DiS., hokejisty HC Oceláři Třinec Václava Varaďu a Jana Peterka, ředitele ostravské pobočky Komerční Banky Mgr. Jiřího Mohylu nebo zástupce UniCredit Bank Ing. Marka Luzara.</p>",
            status : "2",
        }

+ Response 200
+ Response 201

### Smazání tiskové zprávy [DELETE]

+ Parameters
    + id (string) ... ID tiskové zprávy, která má být smazaná.

+ Response 204

# Group Produkty
API pro předávání aktualizovaného seznamu produktů.

## Produkty [/products/{id}]

### Změna / přidání  produktu [POST]
Produkt může být zařazen do jedné a více kategorií dle způsobu nabídky nebo prodeje v restauraci. Dostupné kategorie jsou:

1. mcdonalds
1. mccafe
1. breakfest

+ Request (application/json)

        {
            id : 1,
            location : "cz",
            updated: "10.10.2014 10:10:10",
            title : "Hamburger",
            perex : "<p>Stálice naší nabídky. Mleté hovězí maso s&nbsp;nakládanou okurkou, kečupem a&nbsp;hořčicí. Pšeničná žemle.</p>",
            type : "sandwich",
            category : ["mcdonalds"],
            icon : "http://www.mcdonalds.cz/img/u/produkty/sendvice/ico/hamburger.png",
            photo : "http://www.mcdonalds.cz/img/u/produkty/sendvice/hd/hamburger.png",
            ingredients : ["Mleté hovězí maso", "Pšeničná žemle", "Kečup", "Hořčice", "Nakládaná okurka", "Cibule" ],
            nutrition : [{type : "calories", value : "255", label : "kcal"}, {type : "protein", value : "13"m label : "bílkoviny"}, {type : "fat", value : "9", label : "tuky"}],
            allergens : ["Lepek", "Sezam", "Hořčice"]
        }

+ Response 200
+ Response 201

### Smazání produktu [DELETE]

+ Parameters
    + id (string) ... ID produktu, který má být smazaný.

+ Response 204

# Group Vouchery
API pro předávání aktualizovaného seznamu voucherů.

## Vouchery [/vouchers/{id}]

### Změna / přidání  voucheru [POST]

+ Request (application/json)

        {
            id : 1,
            location : "cz",
            updated: "10.10.2014 10:10:10",
            title : "1 + 1 Chicken McNuggets™ 6 ks",
            photo : "http://www.mcdonalds.cz/img/cs/novinky/slavte-s-nami-nejvyhodneji/kupony/kupon-01.jpg",
            media : ["http://www.mcdonalds.cz/swf/u/novinky/kuponovka/kupon_04.swf"],
            validFrom : "1.9.2014",
            validTo : "30.9.2014"
        }

+ Response 200
+ Response 201

### Smazání voucheru [DELETE]

+ Parameters
    + id (string) ... ID voucheru, který má být smazaný.

+ Response 204

