HOST: http://www.fraus.cz/

--- Frauser API v0.1 ---
---
Popis rozhraní pro práci s Frausery
---

--
Frausery
Tato sekce popisuje rozhraní pro práci s Frausery
--
Zobrazení Frauseru dle jeho id
GET /frauser/{id}
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/frauser/1", "frauserId":"2ZY48XPZ", "metadata": {"name" : "frauser", "created": "30.9.2013"}}
] }


Uloženi frauseru
POST /frauser
> Content-Type: application/json
{ "frauserId":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }


-- Payment Resources --
This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }