FORMAT: 1A
HOST: https://www.mcdonalds.cz

# MCD API
Monet+ API for MCD

Typical API response:

+ 200 OK
+ 400 BAD REQ
+ 410 GONE
+ 404 NOT FOUND
+ 500 INTERNAL ERROR

# Group Login

API for gift card registration and client login.

## Client registration and login [/client-api/client-login]

### Gift card registration [POST]
This method should be used once for client registration. 
After successfull registration client receives e-mail with confirmation link. 
When confirmed, user receives e-mail with password. Each subsequent call should contain
e-mail (username) and password HTTP Basic authentication header.

+ Request (application/json)

        {
            "cln":"1234567890123456", 
            "activationCode":"ABCDEFGH",
            "email":"uzivatel@email.cz"
        }
        
+ Response 200

# Group User account

## User account settings [/client-api/account]

### Query for account settings [POST]

+ Request (application/json)

        {
            "newPassword":"heslo", 
            "firstName":"Franta", 
            "lastName":"Jetel", 
            "birthDate":"19950101",
            "phoneNumber":"+420 123 456 789", 
            "address":"vsechny polozky adresy v jednom? viz navrh designu ...", 
            "sex":"M"
        }
        
+ Response 200


# Group Gift card

## User account balance [/client-api/card/balance]

### Current user acount balance [POST]

+ Request (application/json)
        
        {
            "cln":"1234567890123456"
        }

+ Response 200 (application/json)

        {
            "balance":"20000", "currency":"CZK"
        }
        
## Gift card operations [/client-api/card/block]

### Block gift card [POST]

+ Request (application/json)

        {
            "cln":"1234567890123456", 
            "sendNewCard":true 
        }

+ Response 200 (application/json)

        {}

## Gift card activation [/client-api/card/activation]

### Issue request for new gift card

+ Request (application/json)

        {
            "cln":"1234567890123456", 
            "activationCode":"ABCDEFGH"
        }

+ Response 200

# Group Transactions        

## Transaction overview [/client-api/trx]

### Get list of user's latest transactions [POST]

+ Request (application/json)

        {
            "fromDate":"20140101 12:15:00",
            "toDate":"20140101 12:15:00" 
        }

+ Response 200 (application/json)

        [
            {
                "id":"100123456",
                "amount":"10000",
                "currency":"CZK",
                "created":"20140101 12:15:00"
            },
            { 
                "id":"100123654",
                "amount":"20000",
                "currency":"CZK",
                "created":"20140102 18:15:55"
            }
        ]
        
